/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos (v0.1.54), and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 George MacKerron
Released under the MIT licence: see LICENCE file
*/

import type {
  JSONValue,
  JSONArray,
  DateString,
  SQLFragment,
  SQL,
  GenericSQLExpression,
  ColumnNames,
  ColumnValues,
  ParentColumn,
  DefaultType,
} from "./src/core";


/* === schema: public === */

/* --- enums --- */


/* --- tables --- */

export namespace schema_migrations {
  export type Table = 'schema_migrations';
  export interface Selectable {
    version: string;
  }
  export interface Insertable {
    version: string | SQLFragment;
  }
  export interface Updatable extends Partial<Insertable> { }
  export type Whereable = { [K in keyof Insertable]?: Exclude<Insertable[K] | ParentColumn, null | DefaultType> };
  export type JSONSelectable = { [K in keyof Selectable]:
    Date extends Selectable[K] ? Exclude<Selectable[K], Date> | DateString :
    Date[] extends Selectable[K] ? Exclude<Selectable[K], Date[]> | DateString[] :
    Selectable[K]
  };
  export type UniqueIndex = 'schema_migrations_pkey';
  export type Column = keyof Selectable;
  export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
  export type SQLExpression = GenericSQLExpression | Table | Whereable | Column | ColumnNames<Updatable | (keyof Updatable)[]> | ColumnValues<Updatable>;
  export type SQL = SQLExpression | SQLExpression[];
}

export namespace users {
  export type Table = 'users';
  export interface Selectable {
    id: number;
    name: string;
  }
  export interface Insertable {
    id?: number | DefaultType | SQLFragment;
    name: string | SQLFragment;
  }
  export interface Updatable extends Partial<Insertable> { }
  export type Whereable = { [K in keyof Insertable]?: Exclude<Insertable[K] | ParentColumn, null | DefaultType> };
  export type JSONSelectable = { [K in keyof Selectable]:
    Date extends Selectable[K] ? Exclude<Selectable[K], Date> | DateString :
    Date[] extends Selectable[K] ? Exclude<Selectable[K], Date[]> | DateString[] :
    Selectable[K]
  };
  export type UniqueIndex = 'users_pkey';
  export type Column = keyof Selectable;
  export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
  export type SQLExpression = GenericSQLExpression | Table | Whereable | Column | ColumnNames<Updatable | (keyof Updatable)[]> | ColumnValues<Updatable>;
  export type SQL = SQLExpression | SQLExpression[];
}

/* === cross-table types === */

export type Table = schema_migrations.Table | users.Table;
export type Selectable = schema_migrations.Selectable | users.Selectable;
export type Whereable = schema_migrations.Whereable | users.Whereable;
export type Insertable = schema_migrations.Insertable | users.Insertable;
export type Updatable = schema_migrations.Updatable | users.Updatable;
export type UniqueIndex = schema_migrations.UniqueIndex | users.UniqueIndex;
export type Column = schema_migrations.Column | users.Column;
export type AllTables = [schema_migrations.Table, users.Table];


export type SelectableForTable<T extends Table> = {
  schema_migrations: schema_migrations.Selectable;
  users: users.Selectable;
}[T];

export type WhereableForTable<T extends Table> = {
  schema_migrations: schema_migrations.Whereable;
  users: users.Whereable;
}[T];

export type InsertableForTable<T extends Table> = {
  schema_migrations: schema_migrations.Insertable;
  users: users.Insertable;
}[T];

export type UpdatableForTable<T extends Table> = {
  schema_migrations: schema_migrations.Updatable;
  users: users.Updatable;
}[T];

export type UniqueIndexForTable<T extends Table> = {
  schema_migrations: schema_migrations.UniqueIndex;
  users: users.UniqueIndex;
}[T];

export type ColumnForTable<T extends Table> = {
  schema_migrations: schema_migrations.Column;
  users: users.Column;
}[T];

export type SQLForTable<T extends Table> = {
  schema_migrations: schema_migrations.SQL;
  users: users.SQL;
}[T];

